### PR TITLE
Added missing asdf directory

### PR DESCRIPTION
**Pull request by fairlight1337**
CMake complains when doing INSTALL if this directory is not present (or, more specifially, the .asdf file inside).

### CODE REVIEW

**Comment by airballking** [comment]
I'm skeptical about this change. In the past Bloom would file on symbolic links during releasing. As a reaction, I scrapped all symlinks from this repository.

I'll try to reproduce Jan's original CMake error.

**Comment by airballking** [comment]
Hmm, I just ran ```catkin_make``` and ```catkin_make install``` on a new workspace with only ```roslisp_common``` inside. Both worked fine.

@fairlight1337 What exactly did you do to produce the error?

**Comment by fairlight1337** [comment]
I thought this might be related to an issue I get on the Travis CI build farm:

https://s3.amazonaws.com/archive.travis-ci.org/jobs/51346630/log.txt

Scroll all the way down. Is this actually caused by the missing `asdf` directory?

**Comment by fairlight1337** [comment]
After discussing this in person, I'm closing this as it is deprecated and probably harm-/useless.

**Pull request closed without merging**
