### PR TITLE
Added package cl_urdf

### PR DESCRIPTION
**Pull request by jannikb**
cl_urdf is a package to parse and write urdfs using common lisp.

### CODE REVIEW

**Comment by gaya-** [comment]
* Could you please get rid of the symbolic link to the ```*.asd``` file? It is not necessary and bloom doesn't like it.
* Next time you move big chunks of code try to conserve the git history of that code as well. I find myself looking into the history of certain directories way too often. [How to do that](http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/), [minor fix to the approach from the first link](https://mailman.informatik.uni-bremen.de/pipermail/cram-developers/2014-March/000049.html).

**Comment by gaya-** [comment]
I tested it together with https://github.com/cram-code/cram_physics/pull/22 and it looks fine.
@airballking, feel free to merge both once the minor symbolic link thing is fixed.

**Comment by jannikb** [comment]
Removed the link to the *.asd file.

**Comment by gaya-** [comment]
It's better to put the original file in the root directory. Then you can also delete the asdf directory.

**Comment by jannikb** [comment]
The cl_urdf.asd is in the root directory of cl_urdf and the asdf directory doesn't show up for me anymore.

**Comment by gaya-** [comment]
Ah, true, the mobile interface of Github makes things hard to figure out :)

**Comment by airballking** [comment]
@gaya- thank you for testing this
@jannikb thank you for providing this

**Pull request merged**
